### ISSUE TITLE
Transition to Doctrine ORM

### ISSUE THREAD

**Issue by SierraKomodo** [SierraKomodo/BudgetTracking#2]
# TODO
- [ ] Build TODO list.
- [X] Transition `PDO` to `doctrine/dbal`.
- [x] Transition to `doctrine/orm` with models.
- [x] Add database migrations.
